[package]
name = "tls"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = "1.46.1"
serde_json = "1.0.141"
volga = { path = "../../volga", features = ["tls"] }

[lints]
workspace = true
