[package]
name = "volga-open-api"
version.workspace = true
readme = "README.md"
description = "Volga Open API Integration"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
categories.workspace = true
keywords = ["volga", "openapi", "documentation", "rest-api"]

[dependencies]
http = { workspace = true }
mime = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[features]
problem-details = []

[lints]
workspace = true
