[package]
name = "trace_request"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
volga = { path = "../../volga", features = ["tracing"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
