[package]
name = "dependency_injection"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
uuid = { workspace = true, features = ["v4"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
volga = { path = "../../volga", features = ["middleware", "di"] }

[lints]
workspace = true
