[package]
name = "static_files"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
volga = { path = "../../volga", features = ["static-files", "tracing"] }

[lints]
workspace = true
