name: Bug report
description: Something isn’t working as expected
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! If this is a potential security issue, please use SECURITY.md instead of filing a public issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: "When I do X, I expect Y, but Z happens."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps or a small sample project/snippet.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Volga version
      placeholder: "e.g. 0.8.0"
    validations:
      required: true
  - type: dropdown
    id: runtime
    attributes:
      label: Runtime / environment
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      render: text
      description: Paste relevant logs (redact secrets).
