name: Feature request
description: Suggest an idea or improvement
labels: ["feature", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: "I’m trying to..., but currently..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: "It would be great if Volga could..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "I tried..., but..."
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: "Links, related issues, examples..."
