[package]
name = "request_validation"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = "1.46.1"
volga = { path = "../../volga", features = ["middleware"] }

[lints]
workspace = true
