[package]
name = "oauth_flow"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
volga = { path = "../../volga", features = ["oauth-client"] }
volga-oauth-client = { path = "../../volga-oauth-client" }
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = "0.10.9"
base64 = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "time"] }

[lints]
workspace = true
