[package]
name = "compression"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
volga = { path = "../../volga", features = ["compression-full"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
