[package]
name = "compression"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
volga = { path = "../../volga", features = ["compression-full"] }
serde = "1.0.219"
tokio = "1.46.1"

[lints]
workspace = true
