[package]
name = "global_404_handler"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
volga = { path = "../../volga", features = ["tracing", "di"] }

[lints]
workspace = true
