[package]
name = "cors"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
volga = { path = "../../volga", features = ["middleware","static-files","tracing"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
