[package]
name = "private_cookies"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
uuid = { version = "1.17.0", features = ["v4"] }
tokio = "1.46.1"
volga = { path = "../../volga", features = ["cookie","private-cookie","di"] }

[lints]
workspace = true
