[package]
name = "custom_request_headers"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = "1.46.1"
volga = { path = "../../volga", features = ["middleware", "macros"] }

[lints]
workspace = true
