name: Mirror to Codeberg

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    environment: mirror
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        env:
          TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg https://RomanEmreis:${TOKEN}@codeberg.org/RomanEmreis/volga.git
          git fetch origin main --tags --prune
          git push --force codeberg refs/remotes/origin/main:refs/heads/main
          git push --force --tags codeberg
