name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --all -- --check
        
  clippy_check:
    runs-on: ubuntu-latest
    needs: format_check

    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --locked -- -D warnings

  audit:
    runs-on: ubuntu-latest
    needs: format_check

    steps:
      - uses: actions/checkout@v4
      - name: Security audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  doc_check:
    runs-on: ubuntu-latest
    needs: format_check

    steps:
      - uses: actions/checkout@v4
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --all-features --locked

  build:
    environment: CICD
    runs-on: ubuntu-latest
    needs: [clippy_check, doc_check]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --locked
        
  test:
    environment: CICD
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --locked
    - name: Run tests - Full
      run: cargo test --locked --all-features
    - name: Run tests - http1
      run: cargo test --locked --features http1
    - name: Run tests - http2
      run: cargo test --locked --features http2

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Code coverage check
        run: |
          cargo tarpaulin --locked --all-features --workspace --config coverage.toml --fail-under 80
